"""Dense-storage memory and step-cost table for PRD §12 (Q1/Q2) and §4/§7.4.

Pure arithmetic plus one optional bandwidth measurement on the local CPU. No solver: the
number of field-sized reverse-mode residuals per step (k) is unknown until M2.3 and is
shown as a bracket. Regenerate with:

    uv run python scripts/cost_table.py --measure > reports/dense_cost_table.md
"""

from __future__ import annotations

import argparse
import math
import time

BYTES_FP64 = 8
# Decision §2: the reference is coupon case S03 (CD 500 nm on a 1000 nm pitch, 2500 nm deep), and
# the step count is derived, never written by hand: N = ceil(D / (cfl_target · dx)) at cfl = 0.4.
# The old 512³ / N=500 figures are withdrawn. name -> (shape, N).
DOMAINS = {
    "S03 2D, dx=10": ((270, 100), 625),
    "S03 3D, dx=10 (M2.4 gate)": ((270, 100, 100), 625),
    "S03 2D, dx=5 (V6/V7)": ((540, 200), 1250),
    "S03 3D, dx=5": ((540, 200, 200), 1250),
    "M01 2D, dx=2 (phase 2)": ((1270, 2000), 3125),
}
BUDGETS = (40e9, 80e9)  # decision §7: peak memory under 40 GB on one H100 (80 GB card)
K_BRACKET = (1, 20, 50)  # residual fields per step: 1 = PRD's implicit accounting; 20/50 = op-count bracket
PASSES_BRACKET = (10, 30)  # field-sized reads+writes per forward step (fused), bracket
FLOPS_PER_CELL_STEP = 200  # rough: 2 RK stages × ~70 + ~1 amortised reinit iteration × ~50

# Nominal datasheet peaks (fp64 non-tensor TFLOP/s, HBM TB/s, memory GB). Not re-verified here.
HARDWARE = {
    "H100 SXM": (34.0, 3.35, 80),
    "A100 80GB SXM": (9.7, 2.04, 80),
    "L40S": (1.43, 0.864, 48),
    "RTX 4090": (1.29, 1.008, 24),
}


def fmt_bytes(b: float) -> str:
    for unit, scale in (("TB", 1e12), ("GB", 1e9), ("MB", 1e6), ("kB", 1e3)):
        if b >= scale:
            return f"{b / scale:.3g} {unit}"
    return f"{b:.0f} B"


def fmt_time(s: float) -> str:
    if s >= 1:
        return f"{s:.3g} s"
    if s >= 1e-3:
        return f"{s * 1e3:.3g} ms"
    return f"{s * 1e6:.3g} µs"


def schemes(n: int, k: int) -> dict[str, tuple[float, int]]:
    """Peak stored field-equivalents and extra forward passes of recompute, per scheme."""
    c = math.ceil(math.sqrt(n))
    seg = math.ceil(n / c)
    c_opt = max(1, round(math.sqrt(n * k)))  # two-level with segment length tuned to k
    seg_opt = math.ceil(n / c_opt)
    return {
        "no checkpointing": (n * k, 0),
        "remat step fn only (§7.4 literal)": (n + k, 1),
        f"two-level √N (c={c}, L={seg})": (c + seg * k, 1),
        f"two-level, L tuned to k (c={c_opt}, L={seg_opt})": (c_opt + seg_opt * k, 1),
        f"three-level (c={c}, L={seg}, step remat)": (c + seg + k, 2),
    }


def measure_cpu_pass_seconds(shape: tuple[int, ...]) -> float:
    """Seconds for one jitted, fused fp64 read+write pass over a field (2 field-passes)."""
    import jax

    jax.config.update("jax_enable_x64", True)
    import jax.numpy as jnp

    x = jnp.ones(shape, dtype=jnp.float64)
    f = jax.jit(lambda a: a * 1.0000001 + 1e-9)
    f(x).block_until_ready()
    reps = 20
    t0 = time.perf_counter()
    for _ in range(reps):
        x = f(x)
    x.block_until_ready()
    return (time.perf_counter() - t0) / reps / 2.0  # per single field-pass


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--measure", action="store_true", help="measure local CPU fp64 bandwidth")
    args = ap.parse_args()
    out: list[str] = []
    p = out.append

    p("# Dense level set: memory and step cost (fp64, coupon case S03)")
    p("")
    p("Generated by `scripts/cost_table.py`. Arithmetic, not measurement, except where marked.")
    p("Against the decision §2 reference cases, with N derived from the CFL target (0.4), not assumed.")
    p("")
    p("## 1. Field sizes")
    p("")
    p("| Domain | N | Cells | 1 field fp64 | N×field fp64 (§7.4 'naive') |")
    p("|---|---:|---:|---:|---:|")
    for name, (shape, n) in DOMAINS.items():
        cells = math.prod(shape)
        s = cells * BYTES_FP64
        p(f"| {name} | {n} | {cells:,} | {fmt_bytes(s)} | {fmt_bytes(n * s)} |")
    p("")
    p("## 2. Peak reverse-mode memory by checkpointing scheme")
    p("")
    p("Stored field-equivalents × field size. *k* = field-sized residuals JAX keeps per step for the")
    p("backward pass (unknown until M2.3; k=1 is the PRD's implicit 'store φ only' accounting).")
    p("Excludes static fields (material fractions: n_mat fields), the cotangent carry and XLA scratch,")
    p("so it is a lower bound. Recompute = extra forward passes on top of the original forward.")
    p("")
    for k in K_BRACKET:
        p(f"### k = {k}")
        p("")
        p("| Scheme | recompute | " + " | ".join(DOMAINS) + " |")
        p("|---|---:|" + "---:|" * len(DOMAINS))
        rows: dict[str, list[str]] = {}
        recomputes: dict[str, int] = {}
        for name, (shape, n) in DOMAINS.items():
            for sname, (fields, rec) in schemes(n, k).items():
                key = sname.split(" (")[0]
                rows.setdefault(key, []).append(fmt_bytes(fields * math.prod(shape) * BYTES_FP64))
                recomputes[key] = rec
        for key, cells in rows.items():
            p(f"| {key} | {recomputes[key]}× | " + " | ".join(cells) + " |")
        p("")
    p("## 3. Largest k that fits a memory budget")
    p("")
    p("| Domain | Budget | two-level, L tuned: k ≤ | three-level: k ≤ |")
    p("|---|---:|---:|---:|")
    for name, (shape, n) in DOMAINS.items():
        s = math.prod(shape) * BYTES_FP64
        c = math.ceil(math.sqrt(n))
        seg = math.ceil(n / c)
        for budget in BUDGETS:
            m = budget / s
            k2 = (m * m) / (4 * n)  # 2*sqrt(N k) <= m
            k3 = m - c - seg
            k2s = "does not fit" if k2 < 1 else (f"{k2:.1f}" if k2 < 100 else f"{k2:,.0f}")
            k3s = "does not fit" if k3 < 1 else f"{k3:,.0f}"
            p(f"| {name} | {fmt_bytes(budget)} | {k2s} | {k3s} |")
    p("")
    p("## 4. Forward step cost (roofline lower bound)")
    p("")
    p(f"time/step = max(passes × field / bandwidth, {FLOPS_PER_CELL_STEP} flop/cell × cells / fp64 peak).")
    p("Real stencil code usually reaches 30–60 % of bandwidth, and JIT compile time is excluded.")
    p("Datasheet peaks are nominal and not re-verified here.")
    p("")
    head = "| Hardware | fp64 TF/s | BW TB/s | mem GB | " + " | ".join(
        f"{n} step (10–30 passes)" for n in DOMAINS) + " | gate case, full forward |"
    p(head)
    p("|---|---:|---:|---:|" + "---|" * len(DOMAINS) + "---|")
    rows = dict(HARDWARE)
    measured = None
    if args.measure:
        gate_shape = DOMAINS["S03 3D, dx=10 (M2.4 gate)"][0]
        t_pass = measure_cpu_pass_seconds(gate_shape)
        ref_s = math.prod(gate_shape) * BYTES_FP64
        measured = ref_s / t_pass / 1e12
        rows["this machine CPU (measured BW)"] = (float("nan"), measured, 8)
    for hw, (tf, bw, mem) in rows.items():
        cells_out = []
        ref_fwd = ""
        for name, (shape, n_steps) in DOMAINS.items():
            cells = math.prod(shape)
            s = cells * BYTES_FP64
            ts = []
            for passes in PASSES_BRACKET:
                t_bw = passes * s / (bw * 1e12)
                t_fl = 0.0 if math.isnan(tf) else FLOPS_PER_CELL_STEP * cells / (tf * 1e12)
                ts.append(max(t_bw, t_fl))
            cells_out.append(f"{fmt_time(ts[0])}–{fmt_time(ts[1])}")
            if name.startswith("S03 3D, dx=10"):
                ref_fwd = f"{fmt_time(n_steps * ts[0])}–{fmt_time(n_steps * ts[1])}"
        tf_s = "n/a" if math.isnan(tf) else f"{tf:g}"
        p(f"| {hw} | {tf_s} | {bw:.3g} | {mem} | " + " | ".join(cells_out) + f" | {ref_fwd} |")
    if measured is not None:
        p("")
        p(f"Measured on this machine: one fused fp64 pass over the gate field → {measured * 1e3:.1f} GB/s "
          "effective (jitted `a*x+b`, 20 reps). CPU fp64 flop peak not measured; row is bandwidth-only.")
    p("")
    p("## 5. Reading the table")
    p("")
    p("- The M2.4 gate case is small: one fp64 field is 21.6 MB, so the peak-memory gate of 40 GB")
    p("  (decision §7) is met by simple two-level checkpointing for any plausible k, and the")
    p("  three-level scheme — with its second recompute and the clash with the adjoint-ratio")
    p("  target — is not needed. This is the main consequence of the decision §2 rescoping.")
    p("- `jax.checkpoint` on the step function alone still stores all N carries, so it costs as")
    p("  much as the naive figure. Two-level means a nested scan (decision §7, OPEN_QUESTIONS A4).")
    p("- k, the number of field-sized residuals kept per step, is still unmeasured. Measure it at")
    p("  M2.3 and rerun this table before the M2.4 gate numbers are finalised.")
    p("- Phase-2 M01 at dx = 2 nm is the largest case in the mission and still modest in 2D. Its")
    p("  3D form (1270×2000×2000) would be 40 TB per field and is not planned; phase 2 is 2D.")
    p("- On this 8 GB M1, the 2D cases fit comfortably and the 3D gate case fits for the forward")
    p("  pass; the gate itself belongs on the H100 (decision §6).")
    print("\n".join(out))


if __name__ == "__main__":
    main()
